Repository libsemigroups/libsemigroups, pull requests merged in 2020-01, with the labels that each got.

#150 Release candidate for v1.0.4
  .VERSION
  README.rst
  docs/source/changelog.rst
  docs/source/index.rst
  docs/source/install.rst
Labels: release-candidate

#153 travis: stable-3.2 branch for Semigroups GAP
  ci/docker-gap.sh
Labels: travis

#152 Version info
  Makefile.am
Labels: build-system

#156 Release candidate for v1.0.5
  .VERSION
  README.rst
  docs/source/changelog.rst
  docs/source/index.rst
  docs/source/install.rst
Labels: release-candidate

#174 Makefile.am: resolve Issue #173
  Makefile.am
Labels: distro
