Repository libsemigroups/libsemigroups, pull requests merged in 2022-12, with the labels that each got.

#423 Update version numbers etc for 2.4.0
  README.rst
  docs/source/authors.rst
  docs/source/changelog.rst
  docs/source/index.rst
  docs/source/install.rst
Labels: release-candidate

#428 Add `order_preserving_monoid` presentation
  docs/source/api/fpsemi-examples.rst
  docs/source/libsemigroups.bib
  include/libsemigroups/fpsemi-examples.hpp
  src/fpsemi-examples.cpp
  tests/test-fpsemi-examples-1.cpp
Labels: new-feature

#426 Add presentations for the cyclic inverse monoid, and its order-preserving part
  docs/source/api/fpsemi-examples.rst
  docs/source/libsemigroups.bib
  include/libsemigroups/fpsemi-examples.hpp
  src/fpsemi-examples.cpp
  tests/test-fpsemi-examples-1.cpp
Labels: new-feature

#434 stephen: add Stephen to the README.rst + add some missing doc
  README.rst
  docs/source/index.rst
  include/libsemigroups/stephen.hpp
Labels: doc

#435 present: some fixes to the doc
  docs/yml/presentation.yml
  include/libsemigroups/present.hpp
  include/libsemigroups/present.tpp
Labels: doc
