Repository libsemigroups/libsemigroups, pull requests merged in 2022-09, with the labels that each got.

#362 Add `make<FroidurePin>` from `ActionDigraph`
  Makefile.am
  docs/source/api/make-froidure-pin.rst
  docs/source/semigroups.rst
  include/libsemigroups/make-froidure-pin.hpp
  tests/test-make-froidure-pin.cpp
Labels: new-feature

#348 Add static triangular array container
  include/libsemigroups/containers.hpp
  tests/test-containers.cpp
Labels: new-feature

#369 Replace StaticVector2 by StaticTriVector2
  include/libsemigroups/schreier-sims-helper.hpp
  include/libsemigroups/schreier-sims.hpp
Labels: enhancement, refactor

#370 Modify `SymmetricInverseMonoid` presentation
  tests/fpsemi-examples.cpp
  tests/test-todd-coxeter.cpp
Labels: enhancement

#371 Add `FullTransformationMonoid` and `PartialTransformationMonoid` presentations
  tests/fpsemi-examples.cpp
  tests/fpsemi-examples.hpp
  tests/test-knuth-bendix-6.cpp
  tests/test-sims1.cpp
  tests/test-todd-coxeter.cpp
Labels: enhancement

#384 Fix issue with `replace_subword` and the empty word
  include/libsemigroups/present.tpp
  tests/test-present.cpp
Labels: bug-fix
