Repository libsemigroups/libsemigroups, pull requests merged in 2024-05, with the labels that each got.

#517 V3 work on `fpsemi-examples`
  benchmarks/bench-todd-coxeter.cpp
  benchmarks/bench-todd-coxeter.sh
  docs/Doxyfile
  docs/DoxygenLayout.xml
  docs/fpsemi-examples.md
  docs/source-old/api/fpsemi-examples.rst
  include/libsemigroups/fpsemi-examples.hpp
  src/fpsemi-examples.cpp
  tests/test-fpsemi-examples-1.cpp
  tests/test-fpsemi-examples-2.cpp
  tests/test-fpsemi-examples-3.cpp
  tests/test-todd-coxeter.cpp
Labels: WIP, v3

#545 Add AhoCorasick
  docs/DoxygenLayout.xml
  docs/libsemigroups.bib
  include/libsemigroups/aho-corasick.hpp
  include/libsemigroups/aho-corasick.tpp
  src/aho-corasick.cpp
  src/rewriters.cpp
  tests/test-aho-corasick.cpp
Labels: v3

#541 ci: install libtool for macosx
  .github/workflows/runtests.yml
Labels: CI

#548 doc: sync data structures with pybind11 v1
  docs/Doxyfile
  docs/DoxygenLayout.xml
  etc/make-doc.sh
  include/libsemigroups/forest.hpp
  include/libsemigroups/paths.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/word-graph.hpp
  include/libsemigroups/words.hpp
Labels: doc, v3
