Repository libsemigroups/libsemigroups, pull requests merged in 2024-07, with the labels that each got.

#556 Add Constants
  include/libsemigroups/constants.hpp
Labels: v3

#559 ci: fix macosx job
  .github/workflows/runtests.yml
Labels: v2

#560 Account for non-determinism
  tests/test-todd-coxeter.cpp
Labels: v3

#551 Add Presentation
  benchmarks/bench-todd-coxeter.cpp
  docs/DoxygenLayout.xml
  include/libsemigroups/presentation.hpp
  include/libsemigroups/presentation.tpp
  include/libsemigroups/to-presentation.hpp
  src/fpsemi-examples.cpp
  src/presentation.cpp
  tests/test-cutting.cpp
  tests/test-knuth-bendix-3.cpp
  tests/test-presentation.cpp
  tests/test-sims.cpp
  tests/test-stephen.cpp
  tests/test-todd-coxeter.cpp
Labels: v3

#558 sims: fix issue 557
  include/libsemigroups/sims1.tpp
Labels: bug-fix, v2

#555 Add to_presentation
  Makefile.am
  benchmarks/bench-sims1.cpp
  docs/DoxygenLayout.xml
  include/libsemigroups/presentation.hpp
  include/libsemigroups/sims.hpp
  include/libsemigroups/to-presentation.hpp
  include/libsemigroups/to-presentation.tpp
  src/presentation.cpp
  tests/test-presentation.cpp
  tests/test-to-presentation.cpp
Labels: v3
