Repository libsemigroups/libsemigroups, pull requests merged in 2025-03, with the labels that each got.

#653 Reorganize the CI
  .codecov.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/compile-warnings.yml
  .github/workflows/compilers.yml
  .github/workflows/config-options.yml
  .github/workflows/coverage.yml
  .github/workflows/cpplint.yml
  .github/workflows/downstream.yml
  .github/workflows/os.yml
  .github/workflows/runtests.yml
  .github/workflows/sanitisers.yml
  README.md
  configure.ac
  include/libsemigroups/matrix.hpp
  tests/test-froidure-pin-matrix.cpp
Labels: v3

#655 Resolve issue 618
  include/libsemigroups/word-graph.tpp
  tests/test-word-graph.cpp
Labels: bug-fix, v3

#656 Rename to_string -> to_human_readable_repr for BMat8 + AhoCorasick
  include/libsemigroups/aho-corasick.hpp
  include/libsemigroups/bmat8.hpp
  src/aho-corasick.cpp
  src/bmat8.cpp
  tests/test-bmat8.cpp
Labels: v3

#657 Action: fix the copy assignment operator
  include/libsemigroups/action.hpp
  include/libsemigroups/action.tpp
  tests/test-action.cpp
Labels: v3

#659 Add test for fixme
  include/libsemigroups/obvinf.hpp
  tests/test-obvinf.cpp
Labels: v3

#664 Fix issue with fmt-v11.1.4
  include/libsemigroups/detail/formatters.hpp
  include/libsemigroups/kambites-class.tpp
  include/libsemigroups/matrix.hpp
Labels: v3

#661 Fix more compiler warnings
  include/libsemigroups/todd-coxeter-helpers.hpp
  include/libsemigroups/word-range.hpp
Labels: v3

#666 Remove `[[nodiscard]]` from all `.tpp` files
  include/libsemigroups/transf.tpp
Labels: v3

#668 Fix fixmes 2
  include/libsemigroups/detail/multi-string-view.hpp
  include/libsemigroups/detail/path-iterators.hpp
  include/libsemigroups/detail/path-iterators.tpp
  include/libsemigroups/detail/string.hpp
  include/libsemigroups/detail/todd-coxeter-impl.tpp
  include/libsemigroups/to-presentation.hpp
  include/libsemigroups/to-todd-coxeter.hpp
  include/libsemigroups/word-range.hpp
  src/obvinf.cpp
  tests/test-froidure-pin-transf.cpp
  tests/test-hpcombi.cpp
  tests/test-obvinf.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-todd-coxeter.cpp
  tests/test-word-range.cpp
Labels: v3

#671 Remove old + out of date index.ipynb
  index.ipynb
Labels: v3

#675 Do test todos
  include/libsemigroups/presentation-examples.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/presentation.tpp
  src/bipart.cpp
  src/detail/ke.cpp
  src/detail/todd-coxeter-impl.cpp
  src/presentation-examples.cpp
  tests/test-action.cpp
  tests/test-bitset.cpp
  tests/test-fpsemi-intf.cpp
  tests/test-kambites.cpp
  tests/test-main.cpp
  tests/test-matrix.cpp
  tests/test-paths.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-presentation.cpp
  tests/test-schreier-sims.cpp
  tests/test-todd-coxeter.cpp
  tests/test-word-range.cpp
  tests/word-graph-test-common.hpp
Labels: v3

#673 Check that compile time dim matrices initted from container of same dims
  include/libsemigroups/matrix.hpp
  tests/test-froidure-pin-matrix.cpp
  tests/test-matrix.cpp
Labels: v3

#669 Add tests for `WordGraphWithSources`
  Makefile.am
  include/libsemigroups/detail/word-graph-with-sources.hpp
  tests/test-digraph-with-sources.cpp
  tests/test-word-graph-with-sources.cpp
  tests/test-word-graph.cpp
Labels: v3

#677 Remove report
  .github/workflows/sanitisers.yml
  tests/test-action.cpp
  tests/test-froidure-pin-bipart.cpp
  tests/test-froidure-pin-bmat.cpp
  tests/test-froidure-pin-bmat8.cpp
  tests/test-froidure-pin-integers.cpp
  tests/test-froidure-pin-intpairs.cpp
  tests/test-froidure-pin-matrix.cpp
  tests/test-froidure-pin-maxplustrunc.cpp
  tests/test-froidure-pin-pbr.cpp
  tests/test-froidure-pin-pperm.cpp
  tests/test-froidure-pin-projmaxplus.cpp
  tests/test-froidure-pin-transf.cpp
  tests/test-hpcombi.cpp
  tests/test-kambites.cpp
  tests/test-kbe.cpp
  tests/test-konieczny-bmat.cpp
  tests/test-konieczny-bmat8-1.cpp
  tests/test-konieczny-bmat8-2.cpp
  tests/test-konieczny-bmat8-3.cpp
  tests/test-konieczny-pperm.cpp
  tests/test-konieczny-transf.cpp
  tests/test-matrix.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-race.cpp
  tests/test-runner.cpp
Labels: v3

#637 V3 Stephen
  Makefile.am
  docs/DoxygenLayout.xml
  docs/libsemigroups.bib
  include/libsemigroups/detail/node-managed-graph.tpp
  include/libsemigroups/detail/node-manager.hpp
  include/libsemigroups/detail/node-manager.tpp
  include/libsemigroups/stephen.hpp
  include/libsemigroups/stephen.tpp
  src/stephen.cpp
  tests/test-sims.cpp
  tests/test-stephen.cpp
Labels: v3

#678 Do include todos
  include/libsemigroups/action.hpp
  include/libsemigroups/bitset.hpp
  include/libsemigroups/bmat-adapters.hpp
  include/libsemigroups/bmat8.hpp
  include/libsemigroups/cong-class.hpp
  include/libsemigroups/detail/felsch-graph.hpp
  include/libsemigroups/detail/felsch-graph.tpp
  include/libsemigroups/detail/kbe.tpp
  include/libsemigroups/detail/ke.hpp
  include/libsemigroups/detail/report.hpp
  include/libsemigroups/detail/rewriters.hpp
  include/libsemigroups/dot.hpp
  include/libsemigroups/forest.hpp
  include/libsemigroups/gabow.hpp
  include/libsemigroups/kambites-class.hpp
  include/libsemigroups/knuth-bendix-class.hpp
  include/libsemigroups/matrix.hpp
  include/libsemigroups/obvinf.hpp
  include/libsemigroups/paths.tpp
  include/libsemigroups/presentation-examples.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/presentation.tpp
  include/libsemigroups/ranges.hpp
  include/libsemigroups/sims.hpp
  include/libsemigroups/sims.tpp
  include/libsemigroups/todd-coxeter-class.hpp
  include/libsemigroups/transf.hpp
  include/libsemigroups/ukkonen.hpp
  include/libsemigroups/word-range.hpp
  src/forest.cpp
  src/sims.cpp
  tests/test-action.cpp
Labels: v3

#679 V3 renumber test cases
  etc/test-renumber-all.py
  tests/test-action.cpp
  tests/test-bipart.cpp
  tests/test-cong.cpp
  tests/test-constants.cpp
  tests/test-containers.cpp
  tests/test-forest.cpp
  tests/test-freeband.cpp
  tests/test-froidure-pin-bmat.cpp
  tests/test-froidure-pin-bmat8.cpp
  tests/test-froidure-pin-integers.cpp
  tests/test-froidure-pin-intmat.cpp
  tests/test-froidure-pin-intpairs.cpp
  tests/test-froidure-pin-matrix.cpp
  tests/test-froidure-pin-maxplustrunc.cpp
  tests/test-froidure-pin-pbr.cpp
  tests/test-froidure-pin-pperm.cpp
  tests/test-froidure-pin-projmaxplus.cpp
  tests/test-froidure-pin-transf.cpp
  tests/test-gabow.cpp
  tests/test-iterator.cpp
  tests/test-kambites.cpp
  tests/test-knuth-bendix-2.cpp
  tests/test-knuth-bendix-3.cpp
  tests/test-knuth-bendix-4.cpp
  tests/test-knuth-bendix-5.cpp
  tests/test-knuth-bendix-6.cpp
  tests/test-konieczny-bmat.cpp
  tests/test-konieczny-bmat8-1.cpp
  tests/test-konieczny-bmat8-2.cpp
  tests/test-konieczny-bmat8-3.cpp
  tests/test-konieczny-pperm.cpp
  tests/test-konieczny-transf.cpp
  tests/test-matrix.cpp
  tests/test-obvinf.cpp
  tests/test-presentation.cpp
  tests/test-race.cpp
  tests/test-runner.cpp
  tests/test-schreier-sims.cpp
  tests/test-sims.cpp
  tests/test-stephen.cpp
  tests/test-timer.cpp
  tests/test-to-knuth-bendix.cpp
  tests/test-to-presentation.cpp
  tests/test-to-todd-coxeter.cpp
  tests/test-todd-coxeter.cpp
  tests/test-types.cpp
  tests/test-uf.cpp
  tests/test-ukkonen.cpp
  tests/test-word-graph-with-sources.cpp
Labels: v3

#683 Ctad
  Makefile.am
  include/libsemigroups/hpcombi.hpp
  include/libsemigroups/transf.hpp
  tests/test-action.cpp
  tests/test-bipart.cpp
  tests/test-bmat8.cpp
  tests/test-cong-common.cpp
  tests/test-cong.cpp
  tests/test-felsch-tree.cpp
  tests/test-freeband.cpp
  tests/test-froidure-pin-bipart.cpp
  tests/test-froidure-pin-bmat.cpp
  tests/test-froidure-pin-bmat8.cpp
  tests/test-froidure-pin-intmat.cpp
  tests/test-froidure-pin-matrix.cpp
  tests/test-froidure-pin-maxplustrunc.cpp
  tests/test-froidure-pin-pbr.cpp
  tests/test-froidure-pin-pperm.cpp
  tests/test-froidure-pin-projmaxplus.cpp
  tests/test-froidure-pin-transf.cpp
  tests/test-gabow.cpp
  tests/test-hpcombi.cpp
  tests/test-kambites.cpp
  tests/test-kbe.cpp
  tests/test-knuth-bendix-1.cpp
  tests/test-knuth-bendix-2.cpp
  tests/test-knuth-bendix-5.cpp
  tests/test-matrix.cpp
  tests/test-obvinf.cpp
  tests/test-order.cpp
  tests/test-paths.cpp
  tests/test-pbr.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-presentation-examples-2.cpp
  tests/test-presentation.cpp
  tests/test-rewriters.cpp
  tests/test-schreier-sims.cpp
  tests/test-sims.cpp
  tests/test-stephen.cpp
  tests/test-to-froidure-pin.cpp
  tests/test-to-knuth-bendix.cpp
  tests/test-to-presentation.cpp
  tests/test-to-todd-coxeter.cpp
  tests/test-todd-coxeter.cpp
  tests/test-transf.cpp
  tests/test-ukkonen.cpp
  tests/test-word-graph-with-sources.cpp
  tests/test-word-graph.cpp
  tests/test-word-range.cpp
  tests/word-graph-test-common.hpp
Labels: v3

#583 update Konieczny for v3
  Makefile.am
  docs/DoxygenLayout.xml
  docs/pictures/to-table.tex
  include/libsemigroups/action.tpp
  include/libsemigroups/adapters.hpp
  include/libsemigroups/bipart.hpp
  include/libsemigroups/bmat-adapters.hpp
  include/libsemigroups/detail/pool.hpp
  include/libsemigroups/froidure-pin.tpp
  include/libsemigroups/konieczny.hpp
  include/libsemigroups/konieczny.tpp
  include/libsemigroups/to-froidure-pin.hpp
  include/libsemigroups/to-froidure-pin.tpp
  include/libsemigroups/transf.tpp
  src/runner.cpp
  tests/test-froidure-pin-bipart.cpp
  tests/test-konieczny-bmat.cpp
  tests/test-konieczny-bmat8-1.cpp
  tests/test-konieczny-bmat8-2.cpp
  tests/test-konieczny-bmat8-3.cpp
  tests/test-konieczny-pperm.cpp
  tests/test-konieczny-transf.cpp
Labels: v3

#684 Update readme
  README.md
  docs/DoxygenLayout.xml
Labels: v3

#681 Reduce the number of warnings produced by `make doc`
  docs/Doxyfile
  docs/pictures/to-table.svg
  include/libsemigroups/action.hpp
  include/libsemigroups/adapters.hpp
  include/libsemigroups/aho-corasick.hpp
  include/libsemigroups/bipart.hpp
  include/libsemigroups/bmat-adapters.hpp
  include/libsemigroups/bmat8.hpp
  include/libsemigroups/cong-class.hpp
  include/libsemigroups/cong-common-helpers.hpp
  include/libsemigroups/cong-helpers.hpp
  include/libsemigroups/constants.hpp
  include/libsemigroups/detail/knuth-bendix-impl.hpp
  include/libsemigroups/detail/node-manager.hpp
  include/libsemigroups/detail/rewriters.hpp
  include/libsemigroups/detail/todd-coxeter-impl.hpp
  include/libsemigroups/dot.hpp
  include/libsemigroups/exception.hpp
  include/libsemigroups/forest.hpp
  include/libsemigroups/freeband.hpp
  include/libsemigroups/froidure-pin-base.hpp
  include/libsemigroups/froidure-pin.hpp
  include/libsemigroups/gabow.hpp
  include/libsemigroups/hpcombi.hpp
  include/libsemigroups/kambites-class.hpp
  include/libsemigroups/kambites-helpers.hpp
  include/libsemigroups/knuth-bendix-class.hpp
  include/libsemigroups/knuth-bendix-helpers.hpp
  include/libsemigroups/konieczny.hpp
  include/libsemigroups/matrix.hpp
  include/libsemigroups/obvinf.hpp
  include/libsemigroups/order.hpp
  include/libsemigroups/paths.hpp
  include/libsemigroups/pbr.hpp
  include/libsemigroups/presentation-examples.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/ranges.hpp
  include/libsemigroups/runner.hpp
  include/libsemigroups/schreier-sims.hpp
  include/libsemigroups/sims.hpp
  include/libsemigroups/stephen.hpp
  include/libsemigroups/to-cong.hpp
  include/libsemigroups/to-froidure-pin.hpp
  include/libsemigroups/to-knuth-bendix.hpp
  include/libsemigroups/to-presentation.hpp
  include/libsemigroups/to-todd-coxeter.hpp
  include/libsemigroups/todd-coxeter-class.hpp
  include/libsemigroups/todd-coxeter-helpers.hpp
  include/libsemigroups/transf.hpp
  include/libsemigroups/ukkonen.hpp
  include/libsemigroups/word-graph.hpp
  include/libsemigroups/word-range.hpp
  src/sims.cpp
Labels: v3

#689 Remove #includes from tpp files
  include/libsemigroups/froidure-pin.tpp
  include/libsemigroups/presentation.tpp
  include/libsemigroups/stephen.tpp
  include/libsemigroups/to-todd-coxeter.tpp
  include/libsemigroups/word-graph.tpp
Labels: v3

#690 perf: improve perf of is_acyclic
  include/libsemigroups/bipart.hpp
  include/libsemigroups/detail/path-iterators.hpp
  include/libsemigroups/detail/path-iterators.tpp
  include/libsemigroups/word-graph.hpp
  include/libsemigroups/word-graph.tpp
  tests/test-todd-coxeter.cpp
Labels: v3

#688 Better names than "validate"
  benchmarks/bench-sims1.cpp
  include/libsemigroups/action.hpp
  include/libsemigroups/action.tpp
  include/libsemigroups/aho-corasick.hpp
  include/libsemigroups/bipart.hpp
  include/libsemigroups/cong-class.hpp
  include/libsemigroups/cong-class.tpp
  include/libsemigroups/detail/cong-common-class.hpp
  include/libsemigroups/detail/cong-common-class.tpp
  include/libsemigroups/detail/felsch-graph.tpp
  include/libsemigroups/detail/knuth-bendix-impl.hpp
  include/libsemigroups/detail/knuth-bendix-impl.tpp
  include/libsemigroups/detail/todd-coxeter-impl.hpp
  include/libsemigroups/gabow.hpp
  include/libsemigroups/gabow.tpp
  include/libsemigroups/hpcombi.hpp
  include/libsemigroups/kambites-class.hpp
  include/libsemigroups/kambites-class.tpp
  include/libsemigroups/knuth-bendix-class.hpp
  include/libsemigroups/knuth-bendix-helpers.tpp
  include/libsemigroups/konieczny.hpp
  include/libsemigroups/konieczny.tpp
  include/libsemigroups/matrix.hpp
  include/libsemigroups/obvinf.hpp
  include/libsemigroups/pbr.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/presentation.tpp
  include/libsemigroups/sims.hpp
  include/libsemigroups/sims.tpp
  include/libsemigroups/stephen.hpp
  include/libsemigroups/stephen.tpp
  include/libsemigroups/to-froidure-pin.hpp
  include/libsemigroups/to-froidure-pin.tpp
  include/libsemigroups/to-presentation.hpp
  include/libsemigroups/to-presentation.tpp
  include/libsemigroups/todd-coxeter-class.hpp
  include/libsemigroups/todd-coxeter-class.tpp
  include/libsemigroups/todd-coxeter-helpers.tpp
  include/libsemigroups/transf.hpp
  include/libsemigroups/transf.tpp
  src/aho-corasick.cpp
  src/bipart.cpp
  src/detail/todd-coxeter-impl.cpp
  src/presentation.cpp
  tests/test-bipart.cpp
  tests/test-felsch-tree.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-presentation.cpp
  tests/test-sims.cpp
  tests/test-stephen.cpp
  tests/test-to-presentation.cpp
  tests/test-todd-coxeter.cpp
Labels: v3

#693 Update the nav bar and fix some doc bugs
  docs/Doxyfile
  docs/DoxygenLayout.xml
  docs/install.md
  etc/check_doxygen_line_breaks.py
  etc/make-doc.sh
  include/libsemigroups/action.hpp
  include/libsemigroups/adapters.hpp
  include/libsemigroups/aho-corasick.hpp
  include/libsemigroups/bipart.hpp
  include/libsemigroups/bmat-fastest.hpp
  include/libsemigroups/bmat8.hpp
  include/libsemigroups/detail/report.hpp
  include/libsemigroups/gabow.hpp
  include/libsemigroups/hpcombi.hpp
  include/libsemigroups/matrix.hpp
  include/libsemigroups/obvinf.hpp
  include/libsemigroups/paths.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/sims.hpp
  include/libsemigroups/transf.hpp
  include/libsemigroups/ukkonen.hpp
  include/libsemigroups/word-graph.hpp
  include/libsemigroups/word-range.hpp
Labels: doc, v3

#692 Reclassify tests
  tests/test-cong.cpp
  tests/test-froidure-pin-transf.cpp
  tests/test-hpcombi.cpp
  tests/test-knuth-bendix-4.cpp
  tests/test-konieczny-bmat8-2.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-schreier-sims.cpp
  tests/test-sims.cpp
  tests/test-stephen.cpp
  tests/test-todd-coxeter.cpp
  tests/test-word-range.cpp
Labels: v3, tests

#697 More doc fixes
  .github/workflows/clang-format-check.yml
  .github/workflows/config-options.yml
  .github/workflows/coverage.yml
  .github/workflows/cpplint.yml
  .github/workflows/downstream.yml
  .github/workflows/os.yml
  .github/workflows/runtests.yml
  .github/workflows/sanitisers.yml
  CITATION.cff
  README.md
  docs/DoxygenLayout.xml
  docs/libsemigroups.bib
  include/libsemigroups/bipart.hpp
  include/libsemigroups/forest.hpp
  include/libsemigroups/matrix.hpp
  include/libsemigroups/paths.hpp
  include/libsemigroups/presentation.hpp
  include/libsemigroups/schreier-sims.hpp
  include/libsemigroups/sims.hpp
Labels: v3

#699 Proper attribution for symmetric_inverse_monoid_Gay18
  .github/workflows/os.yml
  benchmarks/bench-sims1.cpp
  docs/libsemigroups.bib
  include/libsemigroups/presentation-examples.hpp
  src/presentation-examples.cpp
  tests/test-presentation-examples-1.cpp
  tests/test-sims.cpp
Labels: v3

#704 Fix issue #703
  Makefile.am
Labels: build-system
