Repository libsemigroups/libsemigroups, pull requests merged in 2025-05, with the labels that each got.

#728 Make `check_doxygen_line_breaks.py` compatible with Python 3.9
  etc/check_doxygen_line_breaks.py
  etc/make-doc.sh
Labels: doc

#729 action: fix add_seed issue
  include/libsemigroups/action.tpp
  tests/test-action.cpp
Labels: bug-fix

#733 build: properly set `FMT_HEADER_ONLY`
  Makefile.am
  include/libsemigroups/detail/fmt.hpp
  m4/ax_check_fmt.m4
Labels: build-system

#731 to: fix `to<Presentation>(kb)`
  include/libsemigroups/to-presentation.hpp
  include/libsemigroups/to-presentation.tpp
  tests/test-knuth-bendix-2.cpp
  tests/test-to-presentation.cpp
Labels: bug-fix
